from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
RESULTS_DIR = ROOT_DIR / "results"
MODELNET40_H5_ROOT = ROOT_DIR / "data_cg" / "ModelNet40_h5" / "modelnet40_ply_hdf5_2048"
SCANOBJECTNN_ROOT = ROOT_DIR / "data_cg" / "ScanObjectNN" / "main_split_nobg"

# ScanObjectNN 的内置兜底类名，若映射文件缺失则使用这一份。
SCANOBJECTNN_CLASS_NAMES = [
    "bag",
    "bin",
    "box",
    "cabinet",
    "chair",
    "desk",
    "display",
    "door",
    "shelf",
    "table",
    "bed",
    "pillow",
    "sink",
    "sofa",
    "toilet",
]


# 这里直接写死 4 组实验配置，符合课程项目“够用即可”的边界。
EXPERIMENTS = {
    "pointnet_modelnet40": {
        "exp_name": "pointnet_modelnet40",
        "model_name": "pointnet",
        "dataset_name": "modelnet40_h5",
        "data_root": MODELNET40_H5_ROOT,
        "num_classes": 40,
        "num_points": 1024,
        "batch_size": 32,
        "test_batch_size": 32,
        "epochs": 100,
        "num_workers": 4,
        "seed": 42,
        "optimizer_name": "adam",
        "lr": 0.001,
        "weight_decay": 0.0,
        "scheduler_name": "step",
        "step_size": 20,
        "gamma": 0.5,
        "feature_transform": True,
        "emb_dims": 1024,
        "dropout": 0.3,
        "k": 20,
        "results_root": RESULTS_DIR,
    },
    "dgcnn_modelnet40": {
        "exp_name": "dgcnn_modelnet40",
        "model_name": "dgcnn",
        "dataset_name": "modelnet40_h5",
        "data_root": MODELNET40_H5_ROOT,
        "num_classes": 40,
        "num_points": 1024,
        "batch_size": 32,
        "test_batch_size": 32,
        "epochs": 100,
        "num_workers": 4,
        "seed": 42,
        "optimizer_name": "sgd",
        "lr": 0.1,
        "momentum": 0.9,
        "weight_decay": 1e-4,
        "scheduler_name": "cosine",
        "feature_transform": False,
        "emb_dims": 1024,
        "dropout": 0.5,
        "k": 20,
        "results_root": RESULTS_DIR,
    },
    "pointnet_scanobjectnn": {
        "exp_name": "pointnet_scanobjectnn",
        "model_name": "pointnet",
        "dataset_name": "scanobjectnn_h5",
        "data_root": SCANOBJECTNN_ROOT,
        "num_classes": 15,
        "num_points": 1024,
        "batch_size": 32,
        "test_batch_size": 32,
        "epochs": 100,
        "num_workers": 4,
        "seed": 42,
        "optimizer_name": "adam",
        "lr": 0.001,
        "weight_decay": 0.0,
        "scheduler_name": "step",
        "step_size": 20,
        "gamma": 0.5,
        "feature_transform": True,
        "emb_dims": 1024,
        "dropout": 0.3,
        "k": 20,
        "results_root": RESULTS_DIR,
    },
    "dgcnn_scanobjectnn": {
        "exp_name": "dgcnn_scanobjectnn",
        "model_name": "dgcnn",
        "dataset_name": "scanobjectnn_h5",
        "data_root": SCANOBJECTNN_ROOT,
        "num_classes": 15,
        "num_points": 1024,
        "batch_size": 32,
        "test_batch_size": 32,
        "epochs": 100,
        "num_workers": 4,
        "seed": 42,
        "optimizer_name": "sgd",
        "lr": 0.1,
        "momentum": 0.9,
        "weight_decay": 1e-4,
        "scheduler_name": "cosine",
        "feature_transform": False,
        "emb_dims": 1024,
        "dropout": 0.5,
        "k": 20,
        "results_root": RESULTS_DIR,
    },
}
